const assert=require('node:assert/strict');
const core=require('../device/core');
const abc='X:1\nM:4/4\nL:1/32\nV: Vocal clef=treble name="Vocal"\nV: Ins clef=bass name="Bass / harmony"\nK:Dm\n% verse\nV: Vocal\n"Dm"=D8-=D8 z16|\n[V: Vocal]"A7"^C16 z16|\nV: Ins\n=D,32-|\n=D,16 =A,16|';
const settings={style:'80s synth',lyrics:'Keep these words',seed:42};
const inst=core.prompt({...settings,renderMode:'instrumental'},abc,8)['9'].inputs;
assert.equal(inst.lyrics,'');assert.match(inst.style,/^Instrumental only/);
assert.ok(inst.abc.includes('"Dm"z8z8 z16|'));
assert.ok(inst.abc.includes('[V: Vocal]"A7"z16 z16|'));
assert.ok(inst.abc.includes('=D,32-|\n=D,16 =A,16|'));
assert.ok(!inst.abc.includes('Harmony'));
const vocal=core.prompt({...settings,renderMode:'vocals'},abc,8)['9'].inputs;
assert.ok(vocal.abc.includes('"Dm"=D8-=D8 z16|'));
assert.ok(vocal.abc.includes('V: Ins\nz32|\nz16 z16|'));
assert.equal(vocal.lyrics,settings.lyrics);
const combined=core.prompt({...settings,renderMode:'combined'},abc,8)['9'].inputs;
assert.equal(combined.abc,abc);assert.equal(combined.lyrics,settings.lyrics);
assert.equal(core.modeABC(vocal.abc,'vocals'),vocal.abc);
assert.equal(core.modeABC(inst.abc,'instrumental'),inst.abc);
assert.equal(core.modeABC(abc.replace(/Vocal/g,'Harmony'),'combined'),abc);
assert.equal(core.modeABC('V: Ins\n[=C^F]10 z2|','vocals'),'V: Ins\nz10 z2|');
assert.equal(core.modeABC('V: Ins\n=C/2 ^F3/2|','vocals'),'V: Ins\nz/2 z3/2|');
assert.throws(()=>core.modeABC('V: Lead\nC8|','vocals'),/unsupported voice/);
assert.throws(()=>core.modeABC('V: Ins\n(3CDE|','vocals'),/Unsupported ABC/);
assert.throws(()=>core.modeABC(abc,'invalid'),/Unknown generation mode/);
const snapshot={tempo:120,numerator:4,denominator:4,root:2,scale:'Minor',clips:[{name:'Bass',role:'bass',looping:true,loopStart:0,loopEnd:4,notes:[{pitch:38,start_time:0,duration:4}]}]};
const source=core.build(snapshot,{bars:1,renderMode:'vocals'}).abc;
assert.equal(source,core.build(snapshot,{bars:1,renderMode:'instrumental'}).abc);
assert.ok(source.includes('=D,,32'));
assert.ok(!core.prompt({...settings,renderMode:'vocals'},source,2)['9'].inputs.abc.includes('=D,,32'));
assert.ok(core.prompt({...settings,renderMode:'combined'},source,2)['9'].inputs.abc.includes('=D,,32'));
console.log('PASS: native voice IDs, targeted rests, chords, durations, ties, legacy labels, invalid syntax, non-destructive source and three request modes.');
